# Performance of Gradual Warping Set Descriptors with DTW as the Baseline

In [24]:
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from dtw import dtw

## Import from local directory
import sys
sys.path.insert(0, '../src')
from TemporalGP.TGP.tgrad_ami import TGradAMI

Configure TGradAMI algorithm hyperparameters.

In [25]:
# Hyperparameters

# f_path = "../datasets/air_quality1k.csv"
# f_path = "../datasets/air_quality25.csv"

f_path_evi = "../datasets/ke_evi_data_2k.csv"
f_path_rain = "../datasets/ke_rain_data_2k.csv"

eq = False
min_sup = 0.5
tgt_col = 1
min_rep = 0.75
mi_err_margin = 0.0001
eval_mode = True
clustering_method = False

Visualize the top 5 rows of the dataset.

In [26]:
rain_data = pd.read_csv(f_path_rain)
evi_data = pd.read_csv(f_path_evi)


print(rain_data.head())
print("\n")
print(evi_data.head())

  Date (Jul-Sep)   NRB (mm)   KAK (mm)   MAK (mm)   WAJ (mm)
0        07-2000   22.01000   526.8000      18.45  12.219990
1        07-2001   57.55001   539.0801       0.90  13.440000
2        07-2002   45.17000   349.2700      20.47  15.320000
3        07-2003   77.08001   660.0199       2.27   8.940001
4        07-2004   16.48000   424.6999       0.71   4.819999


  Date (Jul-Sep)   NRB (EVI)   KAK (EVI)   MAK (EVI)   WAJ (EVI)
0        07-2000    0.094866    0.401556    0.160511    0.120766
1        07-2001    0.236884    0.417010    0.183184    0.152754
2        07-2002    0.243191    0.370047    0.206061    0.109228
3        07-2003    0.202896    0.423199    0.159602    0.109228
4        07-2004    0.119559    0.378931    0.178707    0.099040

Initialize TGradAMI algorithm by creating an object.

In [27]:
t_grad_rain = TGradAMI(f_path_rain, min_sup, eq, target_col=tgt_col, min_rep=min_rep, min_error=mi_err_margin)
t_grad_evi = TGradAMI(f_path_evi, min_sup, eq, target_col=tgt_col, min_rep=min_rep, min_error=mi_err_margin)

Dataset Ok
Dataset Ok

Run the algorithm for mining FTGPs (Fuzzy Temporal Gradual Patterns) in evaluation mode. The algorithm returns a number of results in a dict format. The decomposed gradual pattern components are also returned. This GP component can be used in analyzing multiple timeseries.

In [28]:
eval_dict_rain = t_grad_rain.discover_tgp(use_clustering=clustering_method, eval_mode=eval_mode)
eval_dict_evi = t_grad_evi.discover_tgp(use_clustering=clustering_method, eval_mode=eval_mode)

In [29]:
trans_data_rain = eval_dict_rain['Transformed Data']
trans_data_evi = eval_dict_evi['Transformed Data']

# Put in a dataframe
rain_trans_df = pd.DataFrame(trans_data_rain[1:], columns=t_grad_rain.titles)
evi_trans_df = pd.DataFrame(trans_data_evi[1:], columns=t_grad_evi.titles)

print(rain_trans_df.head())
print("\n")
print(evi_trans_df.head())

  Date (Jul-Sep)  NRB (mm)  KAK (mm)   MAK (mm)  WAJ (mm)
0        07-2000     22.01  539.0801   4.420001     15.32
1        07-2001  57.55001    349.27       6.75  8.940001
2        07-2002     45.17  660.0199       1.51  4.819999
3        07-2003  77.08001  424.6999       1.29     11.81
4        07-2004     16.48  327.3999  0.4299998     23.69


  Date (Jul-Sep)   NRB (EVI)   KAK (EVI)   MAK (EVI)   WAJ (EVI)
0        07-2000  0.09486629  0.41701043  0.18318388  0.10922809
1        07-2001  0.23688364  0.37004653  0.20606092  0.10922809
2        07-2002  0.24319097   0.4231988  0.15960237  0.09904013
3        07-2003  0.20289575   0.3789313  0.17870711  0.09919044
4        07-2004  0.11955917   0.4205146  0.18705401  0.10926049

In [30]:
res_rain_df = t_grad_rain.display_patterns_as_df
res_evi_df = t_grad_evi.display_patterns_as_df

res_rain_df

,Pattern,Support,Density,Avg. Deviation from Diagonal,Rank Dispersion,Graph Connectivity,Singularity Score
0,"NRB (mm)+, (KAK (mm)-) +12.0 months",0.542,0.328,6.602,4.338,1,3.084
1,"NRB (mm)+, (MAK (mm)-) +5.0 years",0.549,0.332,5.917,3.668,1,3.386
2,"NRB (mm)+, (WAJ (mm)-) +2.0 years",0.621,0.375,6.063,4.018,1,3.139

### DTW computations

In [31]:
res_evi_df

,Pattern,Support,Density,Avg. Deviation from Diagonal,Rank Dispersion,Graph Connectivity,Singularity Score
0,"NRB (EVI)+, (KAK (EVI)-) +12.0 months",0.533,0.443,7.643,5.012,1,2.725
1,"NRB (EVI)+, (MAK (EVI)+) +12.0 months",0.514,0.427,7.287,4.886,1,2.618
2,"NRB (EVI)+, (WAJ (EVI)-) +2.0 years",0.629,0.522,7.326,4.678,1,2.469

In [42]:
orig_rain_data = t_grad_rain.data
orig_evi_data = t_grad_evi.data

In [50]:
dtw_data = {"Rain (NRB)": {}, "Transformed Rain (NRB)": {}, "EVI (NRB)": {}, "Transformed EVI (NRB)": {}}

template = None
for i, col in enumerate(t_grad_rain.titles):
    if i in t_grad_rain.time_cols:
        continue
    if i == tgt_col:
        template = orig_rain_data[1:, 1].astype(float)  # NRB
    else:
        query = orig_rain_data[1:, i].astype(float)
        alignment = dtw(query, template, keep_internals=True) if template is not None else None
        if alignment is not None:
            dtw_data["Rain (NRB)"].update({col: float(alignment.distance)})

template = None
for i, col in enumerate(t_grad_rain.titles):
    if i in t_grad_rain.time_cols:
        continue
    if i == tgt_col:
        template = trans_data_rain[1:, 1].astype(float)  # NRB
    else:
        query = trans_data_rain[1:, i].astype(float)
        alignment = dtw(query, template, keep_internals=True) if template is not None else None
        if alignment is not None:
            dtw_data["Transformed Rain (NRB)"].update({col: float(alignment.distance)})

template = None
for i, col in enumerate(t_grad_rain.titles):
    if i in t_grad_rain.time_cols:
        continue
    if i == tgt_col:
        template = orig_evi_data[1:, 1].astype(float)  # NRB
    else:
        query = orig_evi_data[1:, i].astype(float)
        alignment = dtw(query, template, keep_internals=True) if template is not None else None
        if alignment is not None:
            dtw_data["EVI (NRB)"].update({col: float(alignment.distance)})

template = None
for i, col in enumerate(t_grad_rain.titles):
    if i in t_grad_rain.time_cols:
        continue
    if i == tgt_col:
        template = trans_data_evi[1:, 1].astype(float)  # NRB
    else:
        query = trans_data_evi[1:, i].astype(float)
        alignment = dtw(query, template, keep_internals=True) if template is not None else None
        if alignment is not None:
            dtw_data["Transformed EVI (NRB)"].update({col: float(alignment.distance)})

In [53]:
euc_data = {"Rain (NRB)": {}, "Transformed Rain (NRB)": {}, "EVI (NRB)": {}, "Transformed EVI (NRB)": {}}

template = None
for i, col in enumerate(t_grad_rain.titles):
    if i in t_grad_rain.time_cols:
        continue
    if i == tgt_col:
        template = orig_rain_data[1:, 1].astype(float)  # NRB
    else:
        query = orig_rain_data[1:, i].astype(float)
        distance = np.linalg.norm(template - query) if template is not None else None
        if distance is not None:
            euc_data["Rain (NRB)"].update({col: float(distance)})

template = None
for i, col in enumerate(t_grad_rain.titles):
    if i in t_grad_rain.time_cols:
        continue
    if i == tgt_col:
        template = trans_data_rain[1:, 1].astype(float)  # NRB
    else:
        query = trans_data_rain[1:, i].astype(float)
        distance = np.linalg.norm(template - query) if template is not None else None
        if distance is not None:
            euc_data["Transformed Rain (NRB)"].update({col: float(distance)})

template = None
for i, col in enumerate(t_grad_rain.titles):
    if i in t_grad_rain.time_cols:
        continue
    if i == tgt_col:
        template = orig_evi_data[1:, 1].astype(float)  # NRB
    else:
        query = orig_evi_data[1:, i].astype(float)
        distance = np.linalg.norm(template - query) if template is not None else None
        if distance is not None:
            euc_data["EVI (NRB)"].update({col: float(distance)})

template = None
for i, col in enumerate(t_grad_rain.titles):
    if i in t_grad_rain.time_cols:
        continue
    if i == tgt_col:
        template = trans_data_evi[1:, 1].astype(float)  # NRB
    else:
        query = trans_data_evi[1:, i].astype(float)
        distance = np.linalg.norm(template - query) if template is not None else None
        if distance is not None:
            euc_data["Transformed EVI (NRB)"].update({col: float(distance)})

In [54]:
print(dtw_data)
print("\n")
print(euc_data)

{'Rain (NRB)': {'KAK (mm)': 14644.969250000002, 'MAK (mm)': 881.1198715000002, 'WAJ (mm)': 875.599943}, 'Transformed Rain (NRB)': {'KAK (mm)': 11203.31995, 'MAK (mm)': 640.8798911999999, 'WAJ (mm)': 683.859962}, 'EVI (NRB)': {'KAK (mm)': 7.833658126999998, 'MAK (mm)': 1.3506804920000006, 'WAJ (mm)': 0.8294246399999999}, 'Transformed EVI (NRB)': {'KAK (mm)': 7.745991311999999, 'MAK (mm)': 1.243198382, 'WAJ (mm)': 0.7431234929999999}}


{'Rain (NRB)': {'KAK (mm)': 2418.280681351467, 'MAK (mm)': 227.38431920171652, 'WAJ (mm)': 210.92308863621855}, 'Transformed Rain (NRB)': {'KAK (mm)': 2002.402314447756, 'MAK (mm)': 219.92637394210328, 'WAJ (mm)': 198.93260345293277}, 'EVI (NRB)': {'KAK (mm)': 1.166485609427607, 'MAK (mm)': 0.3356889417491932, 'WAJ (mm)': 0.2787018455450198}, 'Transformed EVI (NRB)': {'KAK (mm)': 1.1598661366269634, 'MAK (mm)': 0.331958195129512, 'WAJ (mm)': 0.3217088328491576}}

* We create a Pandas timeseries for each attribute of our transformed dataset.

In [ ]:
trans_time_arr = trans_data_rain[1:, 0]
trans_data_arr = trans_data_rain[1:, 1:]
col_count = trans_data_arr.shape[1]

trans_datetime_series = pd.to_datetime(trans_time_arr, format='%m-%Y')
trans_datetime_index = pd.DatetimeIndex(trans_datetime_series)

lst_trans_ts = []
lst_trans_titles = []
for col in range(col_count):
    trans_ts = pd.Series(trans_data_arr[:, col].astype(float), index=trans_datetime_index)
    lst_trans_titles.append(trans_data_rain[0, col + 1])
    lst_trans_ts.append(trans_ts)

* We plot transformed timeseries to visualize it

In [ ]:
plt.figure(figsize=(16,4))
for i in range(len(lst_trans_ts)):
    plt.plot(trans_datetime_index, lst_trans_ts[i], label=lst_trans_titles[i])
plt.legend()

## Multiple Timeseries Composition using FTGPs

We can use FTGPs to decompose the pairwise object pairs gradual items (GIs) or gradual patterns (GPs) (which are associated with specific attributes/timeseries) into a single scale *warping path* that will allow us to accurately measure the gradual similarity of different timeseries datasets.

* We can visualize the GIs or GPs as shown below.

In [ ]:
## SO4GP Method for getting GP Warping Sets
t_grad_rain.fit_warpingset()
warping_set = t_grad_rain.warping_set

In [ ]:
warping_set.keys()
#warping_set.items()

* We draw numerous plots to visualize the multiple timeseries decompositions using FTGPs. Timeseries data that have strong correlation will produce a decomposition graph with dense zigzag patterns. Those with weak correlation will produce a decomposition graph with sparse zigzag patterns.

In [ ]:
# Calculate the number of rows needed
num_plots = len(warping_set or {})
cols = 4
rows = math.ceil(num_plots / cols)

# Create subplots with the required number of rows and columns
fig, axes = plt.subplots(rows, cols, figsize=(20, rows * 5))
axes = axes.flatten()  # Flatten to make indexing easier

# Plot each component in its subplot
for idx, (key, val) in enumerate(warping_set.items()):
    axes[idx].plot([p[0] for p in val], [p[1] for p in val], '-', label=f"{key}")
    axes[idx].set_xlabel("GP 1 Index")
    axes[idx].set_ylabel("GP 2 Index")
    axes[idx].legend()
    axes[idx].set_title(f"GP Warping Path")

# Hide any extra subplots
for ax in axes[num_plots:]:
    ax.axis("off")

plt.tight_layout()
plt.show()